version: '3.9'

services:
  postgres:
    image: postgres:16.3-alpine
    restart: always
    container_name: postgres-coffee-store
    environment:
      POSTGRES_DB: coffee-store
      POSTGRES_USER: user-coffee-store
      POSTGRES_PASSWORD: password-coffee-store
    ports:
      - "5432:5432"
